
name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
    - name: Test
      run: pytest testing.py
    - name: Lint
      run: pylint add.py
